# Linear algebra numpy

## Vectors: 1D Numpy arrays

<img src='images/1dvector.png'/>

In [116]:
import numpy as np

# define a vector
a = np.array([2, 4, 6, 8])

In [117]:
a

array([2, 4, 6, 8])

In [118]:
a.shape

(4,)

### Operations on vectors

### Addition
The vector must have the same number of dimensions

<img src='images/addition.png' />

In [119]:
a = np.array([2, 3, 4])
b = np.array([5, 6, 7])

In [120]:
a + b

array([ 7,  9, 11])

In [121]:
a.shape, b.shape

((3,), (3,))

### Multiplication by scalar

<img src='images/scalar.png'>

In [122]:
# multiplication by a scalar
3*a

array([ 6,  9, 12])

In [123]:
2*b

array([10, 12, 14])

### Transpose

<img src='images/transpose.png' />

In [124]:
# transpose a
a[np.newaxis, :].T

array([[2],
       [3],
       [4]])

In [125]:
b[np.newaxis, :].T

array([[5],
       [6],
       [7]])

### Linear combinations

In general terms, the simple definition of a linear combination is a multiplication of a scalar to a variable and addition of those terms.

<img src='images/linear_combi.png'/>

In [126]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

a1 = 2
a2 = 3
a3 = 4

In [127]:
v = a1*x + a2*y + a3*z

In [128]:
v

array([42, 51, 60])

## Matrix: 2D numpy array

A Matrix is a two dimensional array that contains the same elements as the vector.A Matrix can have mm rows and nn columns. If a Matrix has mm rows and nn columns is it called an mm x nn matrix.

<img src='images/matrix.png' />

In [129]:
m = np.array([[1, 2, 3], [4, 5, 6]])

In [130]:
m.shape

(2, 3)

In [131]:
m

array([[1, 2, 3],
       [4, 5, 6]])

### Matrix Addition

<img src='images/matrix_addition.png' />

In [132]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[4, 5, 6], [0, 9, 7]])

In [133]:
A + B

array([[ 5,  7,  9],
       [ 4, 14, 13]])

### Scalar Multiplication of Matrix

<img src='images/matrix_A'>

<img src='images/scalar_mul.png'>

In [134]:
alpha = 4
alpha*A

array([[ 4,  8, 12],
       [16, 20, 24]])

### Multiplication of a Square Matrices

<img src='images/matrix_mul.png'/>

if A is an n × m matrix and B is an m × p matrix, their matrix product AB is an n × p matrix, in which the m entries across a row of A are multiplied with the m entries down a column of B and summed to produce an entry of AB. When two linear transformations are represented by matrices, then the matrix product represents the composition of the two transformations.

In [135]:
P = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Q = np.array([[10, 11, 12], [13, 14, 24], [90, 45, 34]])
P.shape, Q.shape

((3, 3), (3, 3))

In [136]:
P*Q

array([[ 10,  22,  36],
       [ 52,  70, 144],
       [630, 360, 306]])